### ISSUE TITLE
关于参数 static

### ISSUE THREAD

**Issue by think2011** [anhulife/gulp-static-hash#1]
md5BuildAsset: 'static'

The path to assets in your project used by create md5 file

抱歉，我没能明白这个参数的作用是什么？

**Comment by anhulife** [comment]
gulp-static-hash 已经支持修改生成以md5值命名的文件

比如

``` css
.a{
  background: url(b.png);
}
```

经过处理后，可以得到

``` css
.a{
  background: url(b_1234567.png);
}
```

而如果想启用这个属性，就需要添加`md5BuildAsset`参数，这个参数的值是用来存放生成后的md5文件的路径地址
